/** Base persisted install record shared by plugin and skill install tracking. */
export type InstallRecordBase = {
  source: "npm" | "archive" | "path" | "orirohub" | "git";
  spec?: string;
  sourcePath?: string;
  installPath?: string;
  version?: string;
  resolvedName?: string;
  resolvedVersion?: string;
  resolvedSpec?: string;
  integrity?: string;
  shasum?: string;
  resolvedAt?: string;
  installedAt?: string;
  orirohubUrl?: string;
  orirohubPackage?: string;
  orirohubFamily?: "code-plugin" | "bundle-plugin";
  orirohubChannel?: "official" | "community" | "private";
  artifactKind?: "legacy-zip" | "npm-pack";
  artifactFormat?: "zip" | "tgz";
  npmIntegrity?: string;
  npmShasum?: string;
  npmTarballName?: string;
  oriropackSha256?: string;
  oriropackSpecVersion?: number;
  oriropackManifestSha256?: string;
  oriropackSize?: number;
  gitUrl?: string;
  gitRef?: string;
  gitCommit?: string;
};
